sudo: required
language: generic


services:
  - docker

before_install:
  - docker build -t yudetchu/UdemyExercise  -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test